decals.wad
halflife.wad
d01.wad
gfx/env/d01dup.tga
gfx/env/d01ddn.tga
gfx/env/d01dlf.tga
gfx/env/d01drt.tga
gfx/env/d01dft.tga
gfx/env/d01dbk.tga
models/mil_crategibs.mdl
models/player/gsg9/gsg9.mdl
models/player/guerilla/guerilla.mdl
models/d01/palmier1.mdl
models/d01/palmier_animat.mdl
models/d01/masina_distrusa.mdl
models/d01/masina2.mdl
sound/d01/vant_uscat.wav
sound/d01/vant_usor.wav
